language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t priyam304/react-client -f Dockerfile.dev ./client

scripts:
  - docker run -e CI=true priyam304/react-client npm run test

after_success:
  - docker build -t priyam304/multi-docker-client ./client/nginx
  - docker build -t priyam304/multi-docker-server ./server 
  - docker build -t priyam304/multi-docker-worker ./worker 
  - docker build -t priyam304/multi-docker-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push priyam304/multi-docker-client
  - docker push priyam304/multi-docker-server
  - docker push priyam304/multi-docker-worker
  - docker push priyam304/multi-docker-nginx